export const SET_USER = 'SET_USER';
export const FETCH_USER_ROLES_START = 'FETCH_USER_ROLES_START';
export const FETCH_USER_ROLES_SUCCESS = 'FETCH_USER_ROLES_SUCCESS';
export const FETCH_USER_ROLES_FAILURE = 'FETCH_USER_ROLES_FAILURE';