import palette from './palette';

export const Typography = {
	fontFamily: ['Lato'].join(','),
	htmlFontSize: 16,
	'@media (min-width:1921px)': { htmlFontSize: 18 },

	h1: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 500,
		fontSize: '4.5rem',
		letterSpacing: '-0.24px',
		lineHeight: '5.625rem',
	},
	h2: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 500,
		fontSize: '3.75rem',
		letterSpacing: '-0.24px',
		lineHeight: '4.5rem',
	},
	h3: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 500,
		fontSize: '2.25rem',
		letterSpacing: '-0.06px',
		lineHeight: '2.75rem',
	},
	h4: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 600,
		fontSize: '1.875rem',
		letterSpacing: '-0.06px',
		lineHeight: '2.375rem',
	},
	h5: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 600,
		fontSize: '1.5rem',
		letterSpacing: '-0.05px',
		lineHeight: '2rem',
	},
	h6: {
		color: palette.text.primary,
		fontFamily: 'Lato',
		fontWeight: 600,
		fontSize: '1.125rem',
		letterSpacing: '-0.05px',
		lineHeight: '1.75rem',
	},
	subtitle1: {
		//color: palette.text.primary,
		fontFamily: 'Lato',
		fontSize: '1.125rem',
		fontWeight: 'normal',
		letterSpacing: '-0.04px',
		lineHeight: '1.875rem',
	},
	subtitle2: {
		//color: palette.text.primary,
		fontFamily: 'Lato',
		fontSize: '1.375rem',
		fontWeight: 'normal',
		letterSpacing: '-0.04px',
		lineHeight: '2rem',
	},
	body1: {
		//color: palette.text.primary,
		fontFamily: 'Lato',
		fontSize: '1rem',
		fontWeight: 'normal',
		letterSpacing: '-0.04px',
		lineHeight: '1.5rem',
	},
	body2: {
		fontFamily: 'Lato',
		fontSize: '0.875rem',
		fontWeight: 'normal',
		letterSpacing: '-0.04px',
		lineHeight: '1.25rem',
	},
	body3: {
		fontFamily: 'Lato',
		fontSize: '0.75rem',
		fontWeight: 'normal',
		letterSpacing: '-0.04px',
		lineHeight: '1.125rem',
	},
	button: {
		fontFamily: 'Lato',
		fontSize: '14px',
	},
	caption: {
		color: palette.text.secondary,
		fontFamily: 'Lato',
		fontSize: '11px',
		letterSpacing: '0.33px',
		lineHeight: '13px',
	},
	overline: {
		//color: palette.text.primary,
		fontFamily: 'Lato',
		fontSize: '11px',
		fontWeight: 500,
		letterSpacing: '0.33px',
		lineHeight: '13px',
		textTransform: 'uppercase',
	},
};

export default Typography;
